version: '3.8'

services:
  propus-spool:
    build:
      context: .
      dockerfile: Dockerfile
    image: propus-spool
    container_name: propus-spool-app
    ports:
      - "8000:8000"
    env_file:
      - .env


networks:
  default:
    name: propus-spool-network
