version: '3.8'

services:
  filaman:
    build:
      context: .
      dockerfile: Dockerfile
    image: filaman-system
    container_name: filaman-system-app
    ports:
      - "8000:8000"
    env_file:
      - .env


networks:
  default:
    name: filaman-network

